catag/catag/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('service/', include('services.urls')),
    path('auth/', include('authorize.urls')),
    path('admin/', admin.site.urls),
]

catag/services/urls.py
# -*- coding: utf-8 -*-
# @Author  : catnlp
# @FileName: urls.py
# @Time    : 2020/7/3 22:21

from django.urls import path

from . import views

app_name = 'services'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('detail/', views.detail, name='detail'),
    path('change/', views.change, name='change'),
]

catag/services/models.py
from django.db import models

# Create your models here.

catag/services/views.py
import json
import numpy as np
import colorsys

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.contrib import auth
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

merge_info = []
gold_info = []
pred_info = []
gold_label = {}
pred_label = {}
gold_pie_legend_data = []
gold_pie_series_data = []
pred_pie_legend_data = []
pred_pie_series_data = []
bar_dataset_source = []
html_texts = []

page = 0
red = '<span style="background:#FF3333;color:white;border-radius:6px;">'
blue = '<span style="background:#209CEE;color:white;border-radius:6px;">'
grey = '<span style="background:#FFCC00;color:white;border-radius:6px;">'
green = '<span style="background:#33CC99;color:white;border-radius:6px;">'
end_span = '</span>'


def _get_colors(num_colors):
    colors = []
    for i in np.arange(0., 360., 360. / num_colors):
        hue = i/360.
        lightness = (50 + np.random.rand() * 10)/100.
        saturation = (90 + np.random.rand() * 10)/100.
        colors.append(colorsys.hls_to_rgb(hue, lightness, saturation))
    return colors


def _get_html_text(text, gold_list, pred_list):
    color_texts = []
    gold_idx = 0
    pred_idx = 0
    while gold_idx < len(gold_list) and \
            pred_idx < len(pred_list):
        gold_start, gold_end, gold_type = gold_list[gold_idx]
        pred_start, pred_end, pred_type = pred_list[pred_idx]
        if gold_start == pred_start and \
                gold_end == pred_end:
            if gold_type == pred_type:
                tmp = green + text[gold_start: gold_end] + end_span
                color_texts.append([gold_start, gold_end, tmp])
            else:
                tmp = grey + text[gold_start: gold_end] + end_span
                color_texts.append([gold_start, gold_end, tmp])
            gold_idx += 1
            pred_idx += 1
        elif gold_start < pred_start and \
                gold_end < pred_end and \
                gold_end > pred_start:
            tmp = red + text[gold_start: pred_start] + end_span
            color_texts.append([gold_start, pred_start, tmp])
            if gold_type == pred_type:
                tmp = green + text[pred_start: gold_end] + end_span
                color_texts.append([pred_start, gold_end, tmp])
            else:
                tmp = grey + text[pred_start: gold_end] + end_span
                color_texts.append([pred_start, gold_end, tmp])
            pred_list[pred_idx][0] = gold_end
            gold_idx += 1
        elif gold_start > pred_start and \
                gold_end > pred_end and \
                gold_start < pred_end:
            tmp = blue + text[pred_start: gold_start] + end_span
            color_texts.append([pred_start, gold_start, tmp])
            if gold_type == pred_type:
                tmp = green + text[gold_start: pred_end] + end_span
                color_texts.append([gold_start, pred_end, tmp])
            else:
                tmp = grey + text[gold_start: pred_end] + end_span
                color_texts.append([gold_start, pred_end, tmp])
            gold_list[gold_idx][0] = pred_end
            pred_idx += 1
        elif gold_start >= pred_start and gold_end <= pred_end:
            if gold_start == pred_start:
                if gold_type == pred_type:
                    tmp = green + text[gold_start: gold_end] + end_span
                    color_texts.append([gold_start, gold_end, tmp])
                else:
                    tmp = grey + text[gold_start: gold_end] + end_span
                    color_texts.append([gold_start, gold_end, tmp])
                pred_list[pred_idx][0] = gold_end
                gold_idx += 1
            else:
                tmp = blue + text[pred_start: gold_start] + end_span
                color_texts.append([pred_start, gold_start, tmp])
                if gold_type == pred_type:
                    tmp = green + text[gold_start: gold_end] + end_span
                    color_texts.append([gold_start, gold_end, tmp])
                else:
                    tmp = grey + text[gold_start: gold_end] + end_span
                    color_texts.append([gold_start, gold_end, tmp])
                if gold_end == pred_end:
                    pred_idx += 1
                else:
                    pred_list[pred_idx][0] = gold_end
                gold_idx += 1
        elif gold_start <= pred_start and gold_end >= pred_end:
            if gold_start == pred_start:
                if gold_type == pred_type:
                    tmp = green + text[pred_start: pred_end] + end_span
                    color_texts.append([pred_start, pred_end, tmp])
                else:
                    tmp = grey + text[pred_start: pred_end] + end_span
                    color_texts.append([pred_start, pred_end, tmp])
                gold_list[gold_idx][0] = pred_end
                pred_idx += 1
            else:
                tmp = red + text[gold_start: pred_start] + end_span
                color_texts.append([gold_start, pred_start, tmp])
                if gold_type == pred_type:
                    tmp = green + text[pred_start: pred_end] + end_span
                    color_texts.append([pred_start, pred_end, tmp])
                else:
                    tmp = grey + text[pred_start: pred_end] + end_span
                    color_texts.append([pred_start, pred_end, tmp])
                if gold_end == pred_end:
                    gold_idx += 1
                else:
                    gold_list[gold_idx][0] = pred_end
                pred_idx += 1
        elif gold_end <= pred_start:
            tmp = red + text[gold_start: gold_end] + end_span
            color_texts.append([gold_start, gold_end, tmp])
            gold_idx += 1
        elif gold_start >= pred_end:
            tmp = blue + text[pred_start: pred_end] + end_span
            color_texts.append([pred_start, pred_end, tmp])
            pred_idx += 1
        else:
            raise RuntimeError("Other situation!")

    while gold_idx < len(gold_list):
        gold_start, gold_end, gold_type = gold_list[gold_idx]
        tmp = red + text[gold_start: gold_end] + end_span
        color_texts.append([gold_start, gold_end, tmp])
        gold_idx += 1

    while pred_idx < len(pred_list):
        pred_start, pred_end, pred_type = pred_list[pred_idx]
        tmp = blue + text[pred_start: pred_end] + end_span
        color_texts.append([pred_start, pred_end, tmp])
        pred_idx += 1

    idx = 0
    html_text = ""
    for color_text in color_texts:
        start, end, ctext = color_text
        if idx < start:
            html_text += text[idx: start]
        html_text += ctext
        idx = end
    if idx < len(text):
        html_text += text[idx: len(text)]

    return html_text


@csrf_exempt
def detail(request):
    global page
    html_text = html_texts[page]
    return render(request, "services/detail.html",
                  {
                      "result": json.dumps(
                          {
                              "text": html_text,
                              "page": page,
                              "total": len(html_texts)
                          })
                  })


@csrf_exempt
def change(request):
    global page
    if request.method == 'GET':
        page = int(request.GET.get('page'))
        if page < 0:
            page = 0
        if page >= len(merge_info):
            page = len(merge_info) - 1
        html_text = html_texts[page]
        return JsonResponse({"text": html_text, "total": len(html_texts)})


@csrf_exempt
def index(request):
    global gold_pie_legend_data
    global gold_pie_series_data
    global pred_pie_legend_data
    global pred_pie_series_data
    global bar_dataset_source
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            request.session['user'] = username  # 将session信息记录到浏览器

            result = {
                "gold_pie_legend_data": gold_pie_legend_data,
                "gold_pie_series_data": gold_pie_series_data,
                "pred_pie_legend_data": pred_pie_legend_data,
                "pred_pie_series_data": pred_pie_series_data,
                "bar_dataset_source": bar_dataset_source
            }
            return render(request, "services/index.html",
                          {"result": json.dumps(result)})
        else:
            return HttpResponseRedirect(reverse('authorize:index'))
    else:
        result = {
            "gold_pie_legend_data": gold_pie_legend_data,
            "gold_pie_series_data": gold_pie_series_data,
            "pred_pie_legend_data": pred_pie_legend_data,
            "pred_pie_series_data": pred_pie_series_data,
            "bar_dataset_source": bar_dataset_source
        }
        return render(request, "services/index.html",
                      {"result": json.dumps(result)})


@csrf_exempt
def upload(request):
    global merge_info
    global gold_label
    global pred_label
    global gold_info
    global pred_info
    global gold_pie_legend_data
    global gold_pie_series_data
    global pred_pie_legend_data
    global pred_pie_series_data
    global bar_dataset_source
    global html_texts
    gold_file = request.FILES.get('gold_file')
    pred_file = request.FILES.get('pred_file')
    if gold_file:
        gold_info = []
        gold_label = {}
        for line in gold_file:
            line = line.decode('UTF-8').rstrip()
            if not line:
                continue
            line = eval(line)
            gold_info.append(line)
            labels = line['label']
            for label in labels:
                label = label[-1]
                if label not in gold_label:
                    gold_label[label] = 1
                else:

catag/services/templates/services/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="catnlp">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>dashboard</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'services/css/bootstrap.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'services/css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Catag</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
<!--        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">-->
<!--          <span>分析</span>-->
<!--          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">-->
<!--            <span data-feather="plus-circle"></span>-->
<!--          </a>-->
<!--        </h6>-->
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'services:index' %}">
              <span data-feather="home"></span>
              概览 <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'services:detail' %}">
              <span data-feather="file"></span>
              详情
            </a>
          </li>
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--              <span data-feather="shopping-cart"></span>-->
<!--              Products-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--              <span data-feather="users"></span>-->
<!--              Customers-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--              <span data-feather="bar-chart-2"></span>-->
<!--              Reports-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--              <span data-feather="layers"></span>-->
<!--              Integrations-->
<!--            </a>-->
<!--          </li>-->
        </ul>

<!--        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">-->
<!--          <span>Saved reports</span>-->
<!--          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">-->
<!--            <span data-feather="plus-circle"></span>-->
<!--          </a>-->
<!--        </h6>-->
<!--        <ul class="nav flex-column mb-2">-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--              <span data-feather="file-text"></span>-->
<!--              Current month-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--              <span data-feather="file-text"></span>-->
<!--              Last quarter-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--              <span data-feather="file-text"></span>-->
<!--              Social engagement-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--              <span data-feather="file-text"></span>-->
<!--              Year-end sale-->
<!--            </a>-->
<!--          </li>-->
<!--        </ul>-->
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
        <script src="{% static 'services/js/echarts.min.js' %}"></script>
        <script src="{% static 'services/js/jquery-3.5.1.min.js' %}"></script>
      {% block content %}{% endblock %}
    </main>
  </div>
</div>

        <script src="{% static 'services/js/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'services/js/feather.min.js' %}"></script>
        <script src="{% static 'services/js/Chart.min.js' %}"></script>
        <script src="{% static 'services/js/dashboard.js' %}"></script>

<!--        <script src="{% static 'services/js/popper.min.js' %}"></script>-->
<!--        <script src="{% static 'services/js/bootstrap.js' %}"></script>-->

  </body>
</html>

catag/services/templates/services/detail.html
{% extends "services/base.html" %}

{% block content %}

    <div align="center" class="justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">详 情</h1>
    </div>
    <div class="container">

<!--      <div class="text-center" >-->
<!--          {% for merge in merges %}-->
<!--              <span>{{ merge.text }} <br /></span>-->
<!--          {% endfor %}-->
<!--      </div>-->
<!--      <br/>-->

<!--      <div class="row">-->
<!--        <div class="col"></div>-->
<!--      <div id="pages" class="text-center">-->
<!--          <nav aria-label="...">-->
<!--              <ul class="pagination">-->
<!--                  <li class="page-item">-->
<!--                    {% if merges.has_previous %}-->
<!--                    <a class="page-link" href="?page={{ merges.previous_page_number }}">上一页</a>-->
<!--                     {% endif %}-->
<!--                  </li>-->
<!--                <li class="page-item">-->
<!--                  <a class="page-link">Page {{ merges.number }} of {{ merges.paginator.num_pages }}</a>-->
<!--                </li>-->
<!--                  <li class="page-item">-->
<!--                    {% if merges.has_next %}-->
<!--                    <a class="page-link" href="?page={{ merges.next_page_number }}">下一页</a>-->
<!--                    {% endif %}-->
<!--                  </li>-->
<!--              </ul>-->
<!--          </nav>-->
<!--      </div>-->
<!--        <div class="col"></div>-->
<!--      </div>-->
        <br/>
        <br/>
        <div class="progress">
          <div id="processBar" class="progress-bar bg-success" role="progressbar" style="width: 1%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <br/>
        <br/>
        <br/>
        <div class="row">
            <div class="col-2">
                <span style="background:#33CC99;color:white;font-size: large;">位置和类型一致</span>
                <br/>
                <span style="background:#FFCC00;color:white;font-size: large;">类型不一致</span>
                <br/>
                <span style="background:#FF3333;color:white;font-size: large;">只有标注实体</span>
                <br/>
                <span style="background:#209CEE;color:white;font-size: large;">只有预测实体</span>
            </div>
            <div class="col-10">
                <div class="shadow p-3 mb-5 bg-white rounded" style="height: 400px">
              <span id="showText" class="text-monospace" style="font-size: x-large;"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div align="center" class="col-3">
                <button type="button" class="btn btn-primary" onclick="previous()">上一页</button>
            </div>
            <div align="center" class="col-4">
                <button id="num_page" type="button" class="btn" style="font-size: large"></button>
            </div>
            <div align="center" class="col-3">
                <button type="button" class="btn btn-primary" onclick="next()">下一页</button>
            </div>
        </div>
      <br/>


      <!-- 显示文件名 -->
      <script>
        var page = 0;
        var total = 0;
        var process_bar = document.getElementById("processBar");
        var result = {{ result|safe }};
        page = result["page"];
        total = result["total"];
        console.log(result);
        if (total === 0){
            process_bar.style.width = "0%";
        }
        else{
            var pos = 100 * (page + 1) / total;
            process_bar.style.width = pos.toString() + "%";
        }

        $("#showText").html(result["text"]);
        $("#num_page").html((page + 1).toString() + "/" + total.toString() + "页");

        function previous() {
            page = page - 1;
            search();
        }

        function next() {
            page = page + 1;
            search();
        }

        function search() {
            $.ajax({
                url:"{% url 'services:change' %}",
                type:"GET",
                data:{"page": page},
                success:function (arg) {
                  $("#showText").html(arg["text"]);
                  total = arg["total"];
                  if (total > 0){
                      var pos = 100 * page / total;

                      process_bar.style.width = pos.toString() + "%";
                      if (total === 0){
                            process_bar.style.width = "0%";
                        }
                        else{
                            pos = 100 * (page + 1) / total;
                            process_bar.style.width = pos.toString() + "%";
                        }
                  }
                  $("#num_page").html((page + 1).toString() + "/" + total.toString() + "页");
                },
                // processData: false,//通过FormData处理数据 jQuery上传文件必须要加这个 tell jQuery not to process the data
                contentType:false,//通过FormData处理数据 jQuery上传文件必须要加这个 tell jQuery not to set contentType
                //以上表示jQuery data数据内容不需要做处理了,把FormData内容发过去给服务器就可以了
            });
        }

      </script>
    </div>

{% endblock %}

catag/services/templates/services/index.html
{% extends "services/base.html" %}

{% block content %}

    <div align="center" class="justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">概 览</h1>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-4">
          <div class="input-group">
            <div class="custom-file">
              <input name="gold_file" onchange="showFilename1(this.files[0])" type="file" class="custom-file-input" id="gold_file" aria-describedby="inputGroupFileAddon04">
              <label id="filename1" class="custom-file-label" for="gold_file">Choose file</label>
            </div>
          </div>
        </div>

        <div class="col">
          <button id="upload1" style="padding: 5px" onclick="AjaxSubmitGoldFile()" class="btn btn-primary">Upload</button>
        </div>

        <div class="col-2"></div>

        <div class="col-4">
          <form enctype="multipart/form-data" action="{% url 'services:upload' %}" method="post">
          <div class="input-group">
            <div class="custom-file">
              <input name="pred_file" onchange="showFilename2(this.files[0])" type="file" class="custom-file-input" id="pred_file" aria-describedby="inputGroupFileAddon04">
              <label id="filename2" class="custom-file-label" for="pred_file">Choose file</label>
            </div>
          </div>
          </form>
        </div>

        <div class="col">
          <button id="upload2" style="padding: 5px" onclick="AjaxSubmitPredFile()" class="btn btn-primary">Upload</button>
        </div>
      </div>

      <div class="justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      </div>

      <br/>
      <div class="row">
        <div class="col">
          <div id="gold_pie" style="align: center; width: 500px;height:500px;"></div>
        </div>
        <div class="col">
          <div id="pred_pie" style="align: center; width: 500px;height:500px;"></div>
        </div>
      </div>

      <div class="justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      </div>

      <div class="row">
        <div class="col">
          <div id="bar" style="align: center; width: 1200px;height:400px;"></div>
        </div>
      </div>


      <!-- 显示文件名 -->
      <script>
        var myBar = echarts.init(document.getElementById('bar'));
        var myGoldPie = echarts.init(document.getElementById('gold_pie'));
        var myPredPie = echarts.init(document.getElementById('pred_pie'));

        // 2.指定图表的配置项和数据 放在option对象里面
        var barOption = {
               title: {
                text: '类别条形图'
              },
              legend: {},
              tooltip: {},
              dataset: {
                  source: [
                      ['类别', '标注', '预测']
                  ]
              },
              xAxis: {type: 'category'},
              yAxis: {},
              // Declare several bar series, each will be mapped
              // to a column of dataset.source by default.
              series: [
                  {type: 'bar'},
                  {type: 'bar'}
              ]
          };

        // 指定图表的配置项和数据 放在option对象里面
          var goldPieOption = {
            title: {
              text: '标注文件饼状图',
              subtext: '类别-数目',
              x: 'center'
            },
            tooltip: {
              trigger: 'item',
              formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
              x: 'center',
              y: 'bottom',
              data: []
            },
            toolbox: {
              show: true,
              feature: {
                mark: { show: true },
                dataView: { show: true, readOnly: false },
                magicType: {
                  show: true,
                  type: ['pie', 'funnel']
                },
                restore: { show: true },
                saveAsImage: { show: true }
              }
            },
            calculable: true,
            series: [
              {
                name: '数目',
                type: 'pie',
                radius: [20, 110],
                center: ['50%', '50%'],
                roseType: 'radius',
                label: {
                  normal: {
                    show: false
                  },
                  emphasis: {
                    show: true
                  }
                },
                lableLine: {
                  normal: {
                    show: false
                  },
                  emphasis: {
                    show: true
                  }
                },
                data: []
              }
            ]
          };

        var predPieOption = {
          title: {
            text: '预测文件饼状图',
            subtext: '类别-数目',
            x: 'center'
          },
          tooltip: {
            trigger: 'item',
            formatter: "{a} <br/>{b} : {c} ({d}%)"
          },
          legend: {
            x: 'center',
            y: 'bottom',
            data: []
          },
          toolbox: {
            show: true,
            feature: {
              mark: { show: true },
              dataView: { show: true, readOnly: false },
              magicType: {
                show: true,
                type: ['pie', 'funnel']
              },
              restore: { show: true },
              saveAsImage: { show: true }
            }
          },
          calculable: true,
          series: [
            {
              name: '数目',
              type: 'pie',
              radius: [10, 110],
              center: ['50%', '50%'],
              roseType: 'radius',
              label: {
                normal: {
                  show: false
                },
                emphasis: {
                  show: true
                }
              },
              lableLine: {
                normal: {
                  show: false
                },
                emphasis: {
                  show: true
                }
              },
              data: []
            }
          ]
        };
        var result = {{ result|safe }};
        console.log(result);
        goldPieOption["legend"]["data"] = result["gold_pie_legend_data"];
        goldPieOption["series"][0]["data"] = result["gold_pie_series_data"];
        predPieOption["legend"]["data"] = result["pred_pie_legend_data"];
        predPieOption["series"][0]["data"] = result["pred_pie_series_data"];
        barOption["dataset"]["source"] = result["bar_dataset_source"];
        myGoldPie.setOption(goldPieOption);
        myPredPie.setOption(predPieOption);
        myBar.setOption(barOption);

        function AjaxSubmitGoldFile() {
            var data = document.getElementById("gold_file").files[0];//加上索引files[0]就是文件的内容,固定写法
            var f = new FormData();
            f.append('gold_file',data);
            $.ajax({
                url:"{% url 'services:upload' %}",
                type:"POST",
                data:f,
                success:function (arg) {
                  goldPieOption["legend"]["data"] = arg["gold_pie_legend_data"];
                  goldPieOption["series"][0]["data"] = arg["gold_pie_series_data"];
                  barOption["dataset"]["source"] = arg["bar_dataset_source"];
                  myGoldPie.setOption(goldPieOption);
                  myBar.setOption(barOption);
                },
                processData: false,//通过FormData处理数据 jQuery上传文件必须要加这个 tell jQuery not to process the data
                contentType:false,//通过FormData处理数据 jQuery上传文件必须要加这个 tell jQuery not to set contentType
                //以上表示jQuery data数据内容不需要做处理了,把FormData内容发过去给服务器就可以了
            });
        }

        function AjaxSubmitPredFile() {
            var data = document.getElementById("pred_file").files[0];//加上索引files[0]就是文件的内容,固定写法
            var f = new FormData();
            f.append('pred_file',data);
            $.ajax({
                url:"{% url 'services:upload' %}",
                type:"POST",
                data:f,
                success:function (arg) {
                  predPieOption["legend"]["data"] = arg["pred_pie_legend_data"];
                  predPieOption["series"][0]["data"] = arg["pred_pie_series_data"];
                  barOption["dataset"]["source"] = arg["bar_dataset_source"];
                  myBar.setOption(barOption);
                  myPredPie.setOption(predPieOption);
                },
                processData: false,//通过FormData处理数据 jQuery上传文件必须要加这个 tell jQuery not to process the data
                contentType:false,//通过FormData处理数据 jQuery上传文件必须要加这个 tell jQuery not to set contentType
                //以上表示jQuery data数据内容不需要做处理了,把FormData内容发过去给服务器就可以了
            });
        }

        function showFilename1(file){
            $("#filename1").html(file.name);
        }
        function showFilename2(file){
            $("#filename2").html(file.name);
        }

      </script>
    </div>

{% endblock %}